/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalfile.gui;

import finalfile.concurrency.UpdateTableThread;
import finalfile.data.DataHelper;
import finalfile.model.Datum;
import finalfile.model.JsonResult;
import finalfile.model.Level2;
import finalfile.model.Level3;
import finalfile.model.XaPhuong;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JProgressBar;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Asus
 */
// so 1
public class MainForm2 extends javax.swing.JFrame {

    /**
     * Creates new form MainForm2
     */
    private static final String currentDir = System.getProperty("user.dir");
    private static final String separator = File.separator;
    private static final String PATH_CSV_FILE = currentDir + separator + "data" + separator + "dvhcvn.json";
    private JProgressBar pgbload;

    public MainForm2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblChiTiet = new javax.swing.JTable();
        pgbLoad = new javax.swing.JProgressBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Lay du lieu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tblChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Xa/Phuong", "Quan/Huyen", "Tinh/Thanh"
            }
        ));
        jScrollPane1.setViewportView(tblChiTiet);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(15, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addComponent(pgbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pgbLoad, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    JsonResult jsonResult;
    //so 2
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        jsonResult = DataHelper.readJsonFile(PATH_CSV_FILE);
        ProgressBarThread pbtThread = new ProgressBarThread(pgbLoad, jsonResult.getData());
        Thread loading = new Thread(pbtThread);
        loading.start();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    //so 3
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm2().setVisible(true);
            }
        });
    }
//so 4
    class ProgressBarThread implements Runnable {

        JProgressBar progessbar;
        List<Datum> data;
        UpdateTableThread udThread;
        Thread updateTable;

        public ProgressBarThread(JProgressBar progessbar, List<Datum> data) {
            this.progessbar = progessbar;
            this.data = data;

        }

        @Override
        public void run() {
            synchronized (pgbload) {
                tblChiTiet.clearSelection();

                DefaultTableModel dtm = (DefaultTableModel) tblChiTiet.getModel();
                dtm.setRowCount(0);
                progessbar.setValue(0);
                List<XaPhuong> danhsachXaPhuong = chiTietXaPhuongs();
                progessbar.setMaximum(danhsachXaPhuong.size());
                XaPhuong XaPhuong;
                for (int i = 0; i < danhsachXaPhuong.size(); i++) {
                    progessbar.setValue(i + 1);
                    XaPhuong = danhsachXaPhuong.get(i);
                    addRow(XaPhuong.getTinhThanh(), XaPhuong.getQuanHuyen(), XaPhuong.getXaPhuong());
                    try {
                        Thread.sleep(5);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(MainForm2.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }

            }
        }

        void addRow(String tinhThanh, String QuanHuyen, String xaPhuong) {
            synchronized (this) {
                udThread = new UpdateTableThread(tinhThanh, QuanHuyen, xaPhuong, tblChiTiet);
                updateTable = new Thread(updateTable);
                updateTable.start();
            }
        }

        List<XaPhuong> chiTietXaPhuongs() {
            List<XaPhuong> ret = new ArrayList<>();
            for (Datum TinhThanh : data) {
                for (Level2 QuanHuyen : TinhThanh.getLevel2s()) {
                    for (Level3 xaPhuong : QuanHuyen.getLevel3s()) {
                        ret.add(new XaPhuong(TinhThanh.getName(), QuanHuyen.getName(), xaPhuong.getName()));
                    }
                }
            }
            return ret;
        }

    }
//so 5
    class UpdateTableThread implements Runnable {

        String tinhThanh;
        String QuanHuyen;
        String xaPhuong;
        JTable table;

        public UpdateTableThread(String tinhThanh, String QuanHuyen, String xaPhuong, JTable table) {
            this.tinhThanh = tinhThanh;
            this.QuanHuyen = QuanHuyen;
            this.xaPhuong = xaPhuong;
            this.table = table;
        }

        @Override
        public void run() {
            System.out.println("log...");
            String[] value = {xaPhuong, QuanHuyen, tinhThanh};

            DefaultTableModel tblModel = (DefaultTableModel) table.getModel();
            tblModel.addRow(value);
            table.scrollRectToVisible(table.getCellRect(table.getRowCount() - 1, 0, true));
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JProgressBar pgbLoad;
    private javax.swing.JTable tblChiTiet;
    // End of variables declaration//GEN-END:variables
}
